# COMP30023 Computer Systems
# 2021 Semester 1
#
# Assignment 1 Makefile
# Created by Syed Ahammad Newaz Saif <snewaz@student.unimelb.edu.au>

allocate:
	gcc -o allocate allocate.c list.c queue.c -lm
clean:
	rm -f allocate